# Generated by Django 4.2.5 on 2023-09-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_visualizer', '0003_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
