# Generated by Django 4.2.5 on 2023-09-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_visualizer', '0005_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='descriptions',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default=None, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='type',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipe_visualizer.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_visualizer.tag')),
            ],
        ),
    ]
